### ISSUE TITLE
Port to 1.20.X Minecraft Fabric

### ISSUE THREAD

**Issue by david-0609** [sylvxa/butterfingers#1]
Hello, I really like your mod and it would be great if you could update it to Minecraft 1.20. Thanks!

**Comment by sylvxa** [comment]
hi there! im working on a port, and it should be out later today. thanks for alerting me!

**Comment by sylvxa** [comment]
updated, working build should be up on the [modrinth page](https://modrinth.com/mod/butterfingers)
